### ISSUE TITLE
Incompatibility with pairsnp >=v0.3.0?

### ISSUE THREAD

**Issue by charlesfoster** [gtonkinhill/fasttranscluster#5]
Hi there,

I tried running `fasttranscluster` with a new installation:

`mamba install -c bioconda pairsnp==0.3.1`
`pip install git+https://github.com/gtonkinhill/fasttranscluster`

 However, I ran into an error:

```
This is pairsnp 0.3.1
Traceback (most recent call last):
  File "/home/cfos/miniconda3/envs/fasttranscluster/bin/fasttranscluster", line 8, in <module>
    sys.exit(main())
  File "/home/cfos/miniconda3/envs/fasttranscluster/lib/python3.7/site-packages/fasttranscluster/__main__.py", line 208, in main
    ncpu=args.n_cpu)
  File "/home/cfos/miniconda3/envs/fasttranscluster/lib/python3.7/site-packages/fasttranscluster/pairsnp.py", line 22, in run_pairsnp
    distances.append([int(t) for t in line.strip().split()])
  File "/home/cfos/miniconda3/envs/fasttranscluster/lib/python3.7/site-packages/fasttranscluster/pairsnp.py", line 22, in <listcomp>
    distances.append([int(t) for t in line.strip().split()])
ValueError: invalid literal for int() with base 10: 'sample1'
```

After trying many things, I eventually tried changing the `pairsnp` versions. Version 0.3.0 had the same error. However, the analysis worked with v0.2.0. Could this please be invstigated?

Thanks,
Charles

**Comment by gtonkinhill** [comment]
Hi Charles,

Thanks for flagging this. I have just pushed a change that should get it working with pairsnp v0.3.1.

I am currently in the process of writing a new package that expands TransCluster to incorporate within-host diversity information and makes some of the outputs more interpretable.  I will update the Readme of this package when the new one is ready and archive this version.
